# Start: docker-compose up -d
# Shutdown: docker-compose down 
# Remove existing volume:  docker volume prune
services:
  mongo:
    image: mongo:6.0.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 9100:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: password
#      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
#    volumes:
#      - mongodb:/data/db

# Names our volume
volumes:
  mongodb:



